const Data = () => {
  const items = [
    {
      id: "001",
      image: "images/1.jpg",
      nail_artist: "Muskaan Wadhwa",
      item_name: "Rhodium-Plated CZ Floral Studs",
      original_price: 990,
      discount_percentage: 42,
      current_price: 574,
    },
    {
      id: "002",
      image: "images/2.jpg",
      nail_artist: "Muskaan Wadhwa",
      item_name: "Rhodium-Plated CZ Floral Studs",
      original_price: 1045,
      discount_percentage: 42,
      current_price: 606,
    },
    {
      id: "003",
      image: "images/3.jpg",
      nail_artist: "Muskaan Wadhwa",
      item_name: "Rhodium-Plated CZ Floral Studs",
      original_price: 1045,
      discount_percentage: 42,
      current_price: 606,
    },
    {
      id: "004",
      image: "images/4.jpg",
      nail_artist: "Muskaan Wadhwa",
      item_name: "Rhodium-Plated CZ Floral Studs",
      original_price: 1045,
      discount_percentage: 42,
      current_price: 606,
    },
    {
      id: "005",
      image: "images/5.jpg",
      nail_artist: "Muskaan Wadhwa",
      item_name: "Rhodium-Plated CZ Floral Studs",
      original_price: 1045,
      discount_percentage: 42,
      current_price: 606,
    },
    {
      id: "006",
      image: "images/6.jpg",
      nail_artist: "Muskaan Wadhwa",
      item_name: "Rhodium-Plated CZ Floral Studs",
      original_price: 1045,
      discount_percentage: 42,
      current_price: 606,
    },
    {
      id: "007",
      image: "images/7.jpg",
      nail_artist: "Muskaan Wadhwa",
      item_name: "Rhodium-Plated CZ Floral Studs",
      original_price: 1045,
      discount_percentage: 42,
      current_price: 606,
    },
    {
      id: "008",
      image: "images/8.jpg",
      nail_artist: "Muskaan Wadhwa",
      item_name: "Rhodium-Plated CZ Floral Studs",
      original_price: 1045,
      discount_percentage: 42,
      current_price: 606,
    },
    {
      id: "009",
      image: "images/9.jpg",
      nail_artist: "Muskaan Wadhwa",
      item_name: "Rhodium-Plated CZ Floral Studs",
      original_price: 1045,
      discount_percentage: 42,
      current_price: 606,
    },
    {
      id: "010",
      image: "images/10.jpg",
      nail_artist: "Muskaan Wadhwa",
      item_name: "Rhodium-Plated CZ Floral Studs",
      original_price: 1045,
      discount_percentage: 42,
      current_price: 606,
    },
    {
      id: "011",
      image: "images/11.jpg",
      nail_artist: "Muskaan Wadhwa",
      item_name: "Rhodium-Plated CZ Floral Studs",
      original_price: 1045,
      discount_percentage: 42,
      current_price: 606,
    },
    {
      id: "012",
      image: "images/12.jpg",
      nail_artist: "Muskaan Wadhwa",
      item_name: "Rhodium-Plated CZ Floral Studs",
      original_price: 1045,
      discount_percentage: 42,
      current_price: 606,
    },
    {
      id: "013",
      image: "images/13.jpg",
      nail_artist: "Muskaan Wadhwa",
      item_name: "Rhodium-Plated CZ Floral Studs",
      original_price: 1045,
      discount_percentage: 42,
      current_price: 606,
    },
    {
      id: "014",
      image: "images/14.jpg",
      nail_artist: "Muskaan Wadhwa",
      item_name: "Rhodium-Plated CZ Floral Studs",
      original_price: 1045,
      discount_percentage: 42,
      current_price: 606,
    },
    {
      id: "015",
      image: "images/15.jpg",
      nail_artist: "Muskaan Wadhwa",
      item_name: "Rhodium-Plated CZ Floral Studs",
      original_price: 1045,
      discount_percentage: 42,
      current_price: 606,
    },
    {
      id: "016",
      image: "images/16.jpg",
      nail_artist: "Muskaan Wadhwa",
      item_name: "Rhodium-Plated CZ Floral Studs",
      original_price: 1045,
      discount_percentage: 42,
      current_price: 606,
    },
    {
      id: "017",
      image: "images/17.jpg",
      nail_artist: "Muskaan Wadhwa",
      item_name: "Rhodium-Plated CZ Floral Studs",
      original_price: 1045,
      discount_percentage: 42,
      current_price: 606,
    },
    {
      id: "018",
      image: "images/18.jpg",
      nail_artist: "Muskaan Wadhwa",
      item_name: "Rhodium-Plated CZ Floral Studs",
      original_price: 1045,
      discount_percentage: 42,
      current_price: 606,
    },
    {
      id: "019",
      image: "images/19.jpg",
      nail_artist: "Muskaan Wadhwa",
      item_name: "Rhodium-Plated CZ Floral Studs",
      original_price: 1045,
      discount_percentage: 42,
      current_price: 606,
    },
    {
      id: "020",
      image: "images/20.jpg",
      nail_artist: "Muskaan Wadhwa",
      item_name: "Rhodium-Plated CZ Floral Studs",
      original_price: 1045,
      discount_percentage: 42,
      current_price: 606,
    },
    {
      id: "021",
      image: "images/21.jpg",
      nail_artist: "Muskaan Wadhwa",
      item_name: "Rhodium-Plated CZ Floral Studs",
      original_price: 1045,
      discount_percentage: 42,
      current_price: 606,
    },
    {
      id: "022",
      image: "images/22.jpg",
      nail_artist: "Muskaan Wadhwa",
      item_name: "Rhodium-Plated CZ Floral Studs",
      original_price: 1045,
      discount_percentage: 42,
      current_price: 606,
    },
    {
      id: "023",
      image: "images/23.jpg",
      nail_artist: "Muskaan Wadhwa",
      item_name: "Rhodium-Plated CZ Floral Studs",
      original_price: 1045,
      discount_percentage: 42,
      current_price: 606,
    },
    {
      id: "024",
      image: "images/24.jpg",
      nail_artist: "Muskaan Wadhwa",
      item_name: "Rhodium-Plated CZ Floral Studs",
      original_price: 1045,
      discount_percentage: 42,
      current_price: 606,
    },
    {
      id: "025",
      image: "images/25.jpg",
      nail_artist: "Muskaan Wadhwa",
      item_name: "Rhodium-Plated CZ Floral Studs",
      original_price: 1045,
      discount_percentage: 42,
      current_price: 606,
    },
  ];
  
  return (
    <>
      {items}
    </>
  )
}

export default Data;