import { createSlice } from "@reduxjs/toolkit";
const items = [
  {
    id: "001",
    image: "/images/products-images/1.png",
    nail_artist: "Muskaan Wadhwa",
    item_name: "Summer Nails",
    original_price: 990,
    discount_percentage: 42,
    current_price: 574,
  },
  {
    id: "002",
    image: "/images/products-images/2.png",
    nail_artist: "Muskaan Wadhwa",
    item_name: "Summer Nails",
    original_price: 1045,
    discount_percentage: 42,
    current_price: 606,
  },
  {
    id: "003",
    image: "/images/products-images/3.png",
    nail_artist: "Muskaan Wadhwa",
    item_name: "Summer Nails",
    original_price: 1045,
    discount_percentage: 42,
    current_price: 606,
  },
  {
    id: "004",
    image: "/images/products-images/4.png",
    nail_artist: "Muskaan Wadhwa",
    item_name: "Summer Nails",
    original_price: 1045,
    discount_percentage: 42,
    current_price: 606,
  },
  {
    id: "005",
    image: "/images/products-images/5.png",
    nail_artist: "Muskaan Wadhwa",
    item_name: "Summer Nails",
    original_price: 1045,
    discount_percentage: 42,
    current_price: 606,
  },
  {
    id: "006",
    image: "/images/products-images/6.png",
    nail_artist: "Muskaan Wadhwa",
    item_name: "Summer Nails",
    original_price: 1045,
    discount_percentage: 42,
    current_price: 606,
  },
  {
    id: "007",
    image: "/images/products-images/7.png",
    nail_artist: "Muskaan Wadhwa",
    item_name: "Summer Nails",
    original_price: 1045,
    discount_percentage: 42,
    current_price: 606,
  },
  {
    id: "008",
    image: "/images/products-images/8.png",
    nail_artist: "Muskaan Wadhwa",
    item_name: "Summer Nails",
    original_price: 1045,
    discount_percentage: 42,
    current_price: 606,
  },
  {
    id: "009",
    image: "/images/products-images/9.png",
    nail_artist: "Muskaan Wadhwa",
    item_name: "Summer Nails",
    original_price: 1045,
    discount_percentage: 42,
    current_price: 606,
  },
  {
    id: "010",
    image: "/images/products-images/10.png",
    nail_artist: "Muskaan Wadhwa",
    item_name: "Summer Nails",
    original_price: 1045,
    discount_percentage: 42,
    current_price: 606,
  },
  {
    id: "011",
    image: "/images/products-images/11.png",
    nail_artist: "Muskaan Wadhwa",
    item_name: "Summer Nails",
    original_price: 1045,
    discount_percentage: 42,
    current_price: 606,
  },
  {
    id: "012",
    image: "/images/products-images/12.png",
    nail_artist: "Muskaan Wadhwa",
    item_name: "Summer Nails",
    original_price: 1045,
    discount_percentage: 42,
    current_price: 606,
  },
  {
    id: "013",
    image: "/images/products-images/13.png",
    nail_artist: "Muskaan Wadhwa",
    item_name: "Summer Nails",
    original_price: 1045,
    discount_percentage: 42,
    current_price: 606,
  },
  {
    id: "014",
    image: "/images/products-images/14.png",
    nail_artist: "Muskaan Wadhwa",
    item_name: "Summer Nails",
    original_price: 1045,
    discount_percentage: 42,
    current_price: 606,
  },
  {
    id: "015",
    image: "/images/products-images/15.png",
    nail_artist: "Muskaan Wadhwa",
    item_name: "Summer Nails",
    original_price: 1045,
    discount_percentage: 42,
    current_price: 606,
  },
  {
    id: "016",
    image: "/images/products-images/16.png",
    nail_artist: "Muskaan Wadhwa",
    item_name: "Summer Nails",
    original_price: 1045,
    discount_percentage: 42,
    current_price: 606,
  },
  {
    id: "017",
    image: "/images/products-images/17.png",
    nail_artist: "Muskaan Wadhwa",
    item_name: "Summer Nails",
    original_price: 1045,
    discount_percentage: 42,
    current_price: 606,
  },
  {
    id: "018",
    image: "/images/products-images/18.png",
    nail_artist: "Muskaan Wadhwa",
    item_name: "Summer Nails",
    original_price: 1045,
    discount_percentage: 42,
    current_price: 606,
  },
  {
    id: "019",
    image: "/images/products-images/19.png",
    nail_artist: "Muskaan Wadhwa",
    item_name: "Summer Nails",
    original_price: 1045,
    discount_percentage: 42,
    current_price: 606,
  },
  {
    id: "020",
    image: "/images/products-images/20.png",
    nail_artist: "Muskaan Wadhwa",
    item_name: "Summer Nails",
    original_price: 1045,
    discount_percentage: 42,
    current_price: 606,
  },
  {
    id: "021",
    image: "/images/products-images/21.png",
    nail_artist: "Muskaan Wadhwa",
    item_name: "Summer Nails",
    original_price: 1045,
    discount_percentage: 42,
    current_price: 606,
  },
  {
    id: "022",
    image: "/images/products-images/22.png",
    nail_artist: "Muskaan Wadhwa",
    item_name: "Summer Nails",
    original_price: 1045,
    discount_percentage: 42,
    current_price: 606,
  },
  {
    id: "023",
    image: "/images/products-images/23.png",
    nail_artist: "Muskaan Wadhwa",
    item_name: "Summer Nails",
    original_price: 1045,
    discount_percentage: 42,
    current_price: 606,
  },
  {
    id: "024",
    image: "/images/products-images/24.png",
    nail_artist: "Muskaan Wadhwa",
    item_name: "Summer Nails",
    original_price: 1045,
    discount_percentage: 42,
    current_price: 606,
  },
];


const homeItemsSlice = createSlice({
  name: 'homeItems',
  initialState: items,
})

export default homeItemsSlice;